stages:
  - test
  - build
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

include:
  - project: brettops/pipelines/pages
    file: include.yml
  - project: brettops/pipelines/prettier
    file: include.yml
  - project: brettops/pipelines/python
    ref: 0.4.0
    file:
      - lint.yml
      - setuptools.yml
      - twine.yml

variables:
  PYTHON_PACKAGE_DIR: badgie

badgie-badges:
  stage: build
  image: ${CONTAINER_PROXY}python:3.11-alpine
  script:
    - pip3 install .
    - mkdir -p public
    - badgie --dump-badge-data > public/badges.json
  artifacts:
    paths:
      - public
